[package]
name = "kse-launcher"
version = "0.9.0"
authors = ["Kai Kramer <kaikramer@users.noreply.github.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "winnt", "minwindef"] }
libloading = "0.7.0"
