[package]
name = "kse-launcher"
version = "0.1.0"
authors = ["Kai Kramer <kaikramer@users.noreply.github.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser", "minwindef"] }
user32-sys = "0.2.0"

